version: "3.3"

services:
  webshell:
    container_name: webshell
    hostname: webshell
    image: ghcr.io/kesokaj/webshell:latest
    volumes:
    - ./data:/home
    environment:
    - TZ=Europe/Stockholm
    - SHELL_USER=<CHANGE ME>
    - SHELL_PASSWORD=<CHANGE ME>
    volumes:
    - ./home:/home
    expose:
    - 80 #gui
    - 8080 #web-preview
    #- 22 #ssh-port --> 2233
    restart: unless-stopped
